# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Dir.glob(`#{Rails.root}/db/seeds/*.rb`).each { |f| require f}
connection = ActiveRecord::Base.connection()

file_array = ["Columbus_Circle_-_Southwest_Park-polygon.shp", "Great_Hill-polygon.shp", "The_North_Woods-polygon.shp", "North_Meadow-polygon.shp", "East_Meadow-polygon.shp", "The_Great_Lawn-polygon.shp", "The_Reservoir-polygon.shp", "Sheep_Meadow-polygon.shp", "Conservatory_Water-polygon.shp", "The_Pond-polygon.shp", "Harlem_Meer-polygon.shp", "The_Lake_South_Shore-polygon.shp", "The_Mall-polygon.shp", "Cedar_Hill-polygon.shp", "The_Ramble-polygon.shp", "Turtle_Pond-polygon.shp"]

file_array.each do |file|
  shp_sql = `shp2pgsql -c -g geom -W LATIN1 -s 4326 #{Rails.root.join('db', 'shapefiles', file)} locations_ref`
  connection.execute "drop table if exists locations_ref"
  connection.execute shp_sql
  connection.execute <<-SQL
      insert into locations(name, geom, created_at, updated_at)
        select name, geom, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP from locations_ref
  SQL
  connection.execute "drop table locations_ref"
end


cheese = User.create(username: "The Cheese", password: "123")




meer = Location.find_by(name: "Harlem Meer")
meer.update(description: "At the northeast end of the park and surrounded by the North Woods, North Meadow, and Conservatory Garden, the Harlem Meer's pastoral pond is
 an absolutely dope place to go for a lazy stroll.")
pond = Location.find_by(name: "The Pond")
pond.update(description: "The southeast corner of the park is often the most crowded with tourists, but sports a gorgeous park, some great activites, and occasionally, one really hot duck.")
meer.landmarks.create(name: "Fort Clinton", description: "Formerly a military fortification during the Revolutionary War and War of 1812, a cannon still marks the spot overlooking the Meer, along with some picnic benches.", image: "https://forgotten-ny.com/wp-content/uploads/2017/05/fort.clinton1.jpg")
meer.landmarks.create(name: "Conservatory Garden", description: "A six acre garden in the middle of New York City, depending on the time of year you'll feel like you're either in The Favourite or The Shining.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/conservatory-garden-l.jpg")
meer.landmarks.create(name: "Lasker Rink and Swimming Pool", description: "Just south of Farmers Gate off the 2/3 train, Lasker Rink is a go-to for swimming during the summer and skating/hockey during the winter. It is currently cancelled though, as it is run by the Trump Organization.", image: "http://michaelminn.net/newyork/parks/central-park/lasker-rink/2004-03-07_16-09-41.jpg")
meer.locimages.create(url: "http://www.centralpark.com/downloads/2613/download/fishing-in-the-meer.jpe?cb=783665e2e86dabe11fdbe675f24e26c4&w=640", alt: "Fishing at the Harlem Meer")


fishing = Interest.create(name: "Fishing")
wildlife = Interest.create(name: "Wildlife")
flora = Interest.create(name: "Flora")
history = Interest.create(name: "History")
art = Interest.create(name: "Art")
architecture = Interest.create(name: "Architecture")
kids = Interest.create(name: "Kids")
hiking = Interest.create(name: "Hiking")
strolling = Interest.create(name: "Strolling")
picnics = Interest.create(name: "Picnics")
exercise = Interest.create(name: "Exercise")
dogs = Interest.create(name: "Dogs")
exercise_tag = exercise.tags.create(tag: "exercise")
dogs_tag = dogs.tags.create(tag: "dogs")
picnics_tag = picnics.tags.create(tag: "picnics")
fishing_tag = fishing.tags.create(tag: "fishing")
wildlife_tag = wildlife.tags.create(tag: "wildlife")
flora_tag = flora.tags.create(tag: "flora")
history_tag = history.tags.create(tag: "history")
architecture_tag = architecture.tags.create(tag: "architecture")
kids_tag = kids.tags.create(tag: "kids")
art_tag = art.tags.create(tag: "art")
hiking_tag = hiking.tags.create(tag: "hiking")
strolling_tag = strolling.tags.create(tag: "strolling")
# Meer
# create_reference_to_tag_by_nameuser_id_and_review(tag, id, review)
meer.create_reference_to_tag_by_name_user_id_and_review("fishing", cheese.id, "In addition to the turtles, there's several excellent places for catch and release.")
meer.create_reference_to_tag_by_name_user_id_and_review("wildlife", cheese.id, "It's just turtles all the way down.")
meer.create_reference_to_tag_by_name_user_id_and_review("flora", cheese.id, "Check out the conservatory garden!")
meer.facts.create(factoid: "Meer is Dutch for lake")
meer.facts.create(factoid: "This meer was once a brackish portion of wetland that drained into the East River.")
meer.locimages.create(url: "https://upload.wikimedia.org/wikipedia/commons/8/89/Dana_Discovery_Center%2C_Central_Park_NY.JPG", alt: "The Dana Discovery Center at the Harlem Meer")
meer.locimages.create(url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Central_Park_New_York_October_2016_panorama_1.jpg/1200px-Central_Park_New_York_October_2016_panorama_1.jpg", alt: "view of water at meer")
# Pond
pond.create_reference_to_tag_by_name_user_id_and_review("kids", cheese.id, "With the Central Park Zoo here as well as rocks for climbing, this is a great place for kids.")
pond.create_reference_to_tag_by_name_user_id_and_review("history", cheese.id, "Nobody burns down Georgia like Sherman.")
pond.create_reference_to_tag_by_name_user_id_and_review("wildlife", cheese.id, "Two words: Hot Duck.")
pond.facts.create(factoid: "The Pond is one of Central Park's seven naturalistic water bodies.")
pond.facts.create(factoid: "The Pond holds Hallett Nature Sanctuary, a wooded promontory with a 3.5-acre ecosystem.")
pond.locimages.create(url: "http://assets.centralparknyc.org/images/things-to-see-and-do/pond-l.jpg", alt: "pond with view of Gapstow Bridge")
pond.locimages.create(url: "https://static01.nyt.com/images/2018/11/02/business/01XP-DUCK/31XP-DUCK-videoSixteenByNine3000.jpg", alt: "Central Park's legendary Hot Duck")
pond.landmarks.create(name: "Central Park Zoo", description: "A zoo, plus a petting zoo, in the heart of the city. Come for the seals, stay for the incredibly energetic red pandas. NY 12th Congressional District Representative Carolyn Maloney has been pushing to get pandas in here for years.", image: "https://c532f75abb9c1c021b8c-e46e473f8aadb72cf2a8ea564b4e6a76.ssl.cf5.rackcdn.com/2016/10/20/9kn6or4r6j_cp_photo_sg_large.jpg")
pond.landmarks.create(name: "Wollman Rink", description: "Can you name a more iconic (or expensive) place to skate in New York City? ...Apart from Rockefeller Center.", image: "https://upload.wikimedia.org/wikipedia/commons/6/66/WollmanRink.jpg")
pond.landmarks.create(name: "Grand Army Plaza", description: "If you want to pay your respects to the guy who absolutely trashed the South, there's a giant statue of General William Tecumseh Sherman at the Southeast corner of the park.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/Sherman-750.jpg")
pond.landmarks.create(name: "Statues of Latin American Leaders", description: "If you want to check out a statue of Simón Bolívar or General José de San Martín, walk along the Southern end of the park.", image: "https://static.wixstatic.com/media/99078f_7faf7be9a7bb440380f8aad14b70e176~mv2_d_1900_1267_s_2.jpg")
pond.landmarks.create(name: "Horse Riding", description: "If you want to waste money like a tourist, Mayor Bill DeBlasio was unsuccessful on his promise to get the horses out of Central Park.", image: "http://www.centralpark.com/downloads/7996/download/Horse%20Carriage%20riders.JPG?cb=c646d57e74c95949370a4b474b132b4e&w=640")


columbus = Location.find_by(name: "Columbus Circle - Southwest Park")
columbus.update(description: "The Southwest corner of the park has walking paths to get lost in and parks and attractions for kids")

columbus.landmarks.create(name: "Central Park Carousel", description: "An iconic carousel, this is a great place to bring kids on the way to Sheep Meadow.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Central_Park_Carousel_snow_jeh.JPG/1920px-Central_Park_Carousel_snow_jeh.JPG")
columbus.landmarks.create(name: "Heckscher Playground", description: "This fountain heavy playground is great for burning off kids' energy.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/heckscher-playground-l.jpg")
columbus.landmarks.create(name: "Columbus Circle", description: "At the Southwest corner of the park, a giant statue of Columbus sits in the center of malls, skateboarders, fountains, and often a holiday market.", image: "https://theknickerbocker.com/wp-content/uploads/2017/02/Columbus-Circle-NYC-Midtown-Guide-Knickerbocker-Hotel.jpg")
columbus.create_reference_to_tag_by_name_user_id_and_review("hiking", cheese.id, "This is a great part of the park to get lost in.")
columbus.create_reference_to_tag_by_name_user_id_and_review("kids", cheese.id, "If you're going to the carousel, watch out. Your kid will not leave without a plastic sword.")
columbus.facts.create(factoid: "The Central Park Carousel heavily featured in Catcher in the Rye.")
columbus.locimages.create(url: "http://assets.centralparknyc.org/images/things-to-see-and-do/greyshot-arch-l.jpg", alt: "Greyshot Arch")
columbus.locimages.create(url: "http://www.starrwhitehouse.com/wp-content/uploads/2018/04/DSC02953-1.jpg", alt: "Summit Rock")


cedar = Location.find_by(name: "Cedar Hill")
cedar.update(description: "A popular hillside meadow, this is a go-to in the park for quiet picnicking in the summer, and sledding in the winter. It also features a number of flowers in spring. It's named for the red cedars on its crest.")
cedar.landmarks.create(name: "Still Hunt Statue", description: "A statue of a crouching panther set directly on top of a ledge of rock, designed by Edward Kemeys, an American sculptor who also worked as an axe-man building central park.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/still-hunt-l.jpg")
cedar.landmarks.create(name: "Glade Arch", description: "An arch originally serving as an access road for carriages, this is a classic example of a Centarl Park arch.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Glade_Arch_north_cloudy_jeh.jpg/2560px-Glade_Arch_north_cloudy_jeh.jpg")
cedar.create_reference_to_tag_by_name_user_id_and_review("picnics", cheese.id, "This is the spot to go for a quieter picnic. Love being stared at by cats of prey while I hang out with my friends and quietly sip from a box of Trader Joe's Red.")
cedar.create_reference_to_tag_by_name_user_id_and_review("dogs", cheese.id, "Pay no attention to the cat statue. Before 9AM, this spot is Woodstock for dogs.")
cedar.facts.create(factoid: "This was the first spot where Central Park tested shutting down portions of the lawn at times when the grass was vulnerable. It's now a common occurance across the park.")
cedar.locimages.create(url: "https://live.staticflickr.com/90/247029617_5d50aae013_b.jpg", alt: "Cedar Hill with sign.")
cedar.locimages.create(url: "https://imgs.6sqft.com/wp-content/uploads/2015/12/20035528/Central-Park-Cedar-Hill-today-1024x711.jpg", alt: "Cedar Hill in the fall.")
cedar.locimages.create(url: "http://www.centralpark.com/downloads/6013/download/Cedar_Hill.jpg.jpe?cb=783665e2e86dabe11fdbe675f24e26c4&w=640", alt: "Cedar Hill sledding in winter.")

ramble = Location.find_by(name: "The Ramble")
ramble.update(description: "Perhaps the section of the park with the most \"nature\" (it's entirely artificial) and easily the most notorious section of the park (frequently appearing as \"the place where they found the body\" in episodes of Law and Order) Central Park's Ramble has served as a gathering spot for New York's hikers, birdwatchers, and serves as an important part of NYC LGBTQ history as a place where LGBTQ people could have private encounters.")
ramble.landmarks.create(name: "Ramble Stone Arch", description: "A bridge with a narrow arch below and covered in foliage, in addition to being gorgeous, it contains the remains of a cave that was covered in the 1920s after a series of crimes.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/ramble-stone-arch-l.jpg")
ramble.landmarks.create(name: "The Point", description: "Protruding into the Lake, this place offers a great vantage point over Bethesday Terrace.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/point-l.jpg")
ramble.landmarks.create(name: "The Gill", description: "A stream that travels the Ramble to the lake, it's actually entirely artificial: It can be turned off like a faucet.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/gill-l.jpg")
ramble.create_reference_to_tag_by_name_user_id_and_review("hiking", cheese.id, "If they unboarded the cave in 2019, it would make a fortune on AirBNB.")
ramble.create_reference_to_tag_by_name_user_id_and_review("dogs", cheese.id, "My dog loves an adventure, but heads up: There are no trash cans in the Ramble. If your dog takes a dump, you're taking it with you.")
ramble.facts.create(factoid: "There are no trash cans in the Ramble.")
ramble.locimages.create(url: "https://i1.wp.com/travellingboomer.com/wp-content/uploads/Central-Park-The-Ramble-sign-1.jpg", alt: "A sign at the entrance to the Ramble.")
ramble.locimages.create(url: "http://www.aviewoncities.com/img/nyc/kveus11259s.jpg", alt: "A bridge in the Ramble.")
ramble.locimages.create(url: "http://www.centralparksunsettours.com/wp-content/uploads/2016/06/IMG_20160624_141258.jpg", alt: "A tree protrudes in front of a rough path in the Ramble.")


sheep = Location.find_by(name: "Sheep Meadow")
sheep.update(description: "Sheep Meadow was designed as a placid expanse, and, without ballfields and with organized sports and gatherings forbidden, it serves as a quiet space in the middle of Central Park.")
sheep.landmarks.create(name: "Tavern on the Green", description: "While this restaurant located in Central Park continues to change hands, as of 2007, at $38 million, it was the second-highest-grossing independent restaurant in the United States, second only to Las Vegas's Tao restaurant at the Venetian.", image: "https://www.nycgo.com/images/venues/5721/headertavern-on-the-green-courtyarda-maura-daley__x_large.jpg")
sheep.landmarks.create(name: "Adventure Playground", description: "Adventure Playground features a conical climber with tunnels and a slide, a fortress, maze-like structures, a circular water spray feature, sand play areas and safety carpet.", image: "https://tclf.org/sites/default/files/features/2015-12-15%20Adventure%20Playground/HistoricAdventurePlayground-2cropped.jpg")
sheep.create_reference_to_tag_by_name_user_id_and_review("picnics", cheese.id, "Get out early if you want to get a spot under a tree in July.")
sheep.create_reference_to_tag_by_name_user_id_and_review("kids", cheese.id, "The Adventure Playground feels fresh after the new renovation.")
sheep.facts.create(factoid: "In the 1960s and 70s, Sheep Meadow became a haven for the hippie movement. After the city government refused to upkeep it in the face of hippies, it was a virtual dust bowl by the 1970s.")
sheep.locimages.create(url: "https://www.walksofnewyork.com/blog/wp-content/uploads/2012/04/Sheep-Meadow.jpg", alt: "Sheep Meadow in the summer.")
sheep.locimages.create(url: "https://outbuzz.com/wp-content/uploads/2017/08/second-sundays-central-park.jpg", alt: "Crowded summer Sheep Meadow.")


mall = Location.find_by(name: "The Mall")
mall.update(description: "The only formalistic section of Central Park, this iconic walk leading from the Literary Walk to Bethesda Fountain was a favored place for the rich to mingle with the lower classes in an afternoon stroll at the the turn of the 20th century.")
mall.landmarks.create(name: "Literary Walk", description: "A statuary devoted to the great figures of literature, it contains statues of William Shakespeare, Sir Walter Scott, Robert Burns, and more.", image: "https://www.nycgo.com/images/venues/2975/literary-walk-will-steacy-8__x_large.jpg")
mall.landmarks.create(name: "Balto Statue", description: "A statue to the dog hero of Nome, just visiting it gets you within two degrees of Kevin Bacon (the Disney film Balto, which he starred in, ends with a shot of this statue).", image: "http://www.centralpark.com/downloads/7892/download/Balto.jpg?cb=fc63c0c9515ce5c7d341e9da08f89ec4&w=640")
mall.landmarks.create(name: "Rumsey Playfield", description: "The site of numerous events including the SummerStage event festival, you can picnic outside and hear the music for free.", image: "http://www.centralpark.com/downloads/5626/download/summerstage.jpg.jpe?cb=783665e2e86dabe11fdbe675f24e26c4")
mall.landmarks.create(name: "307th Infantry Regiment Memorial Grove", description: "The 307th Infantry Regiment Memorial Grove is an area dedicated to the memory of soldiers who gave their lives during World War I. Following the war, several young trees were planted in the grove- one for each of the Regiment’s companies. Each tree was marked with a plaque containing the names of men in that company who died in battle.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/307-infantry-memorial-grove.jpg")
mall.create_reference_to_tag_by_name_user_id_and_review("kids", cheese.id, "A statue to a dog in a Disney movie. This is simply the best way to a kid's heart.")
mall.create_reference_to_tag_by_name_user_id_and_review("history", cheese.id, "The Memorial Grove is a classy and understated thing to stumble into.")
mall.create_reference_to_tag_by_name_user_id_and_review("strolling", cheese.id, "Love strolling down the mall feeling like old timey 5th Avenue aristocracy.")
mall.create_reference_to_tag_by_name_user_id_and_review("art", cheese.id, "Murdered a guy for Shakespeare in the Park tickets.")
mall.facts.create(factoid: "Shakespeare's roots run deep in this area. An early fixture of New York City entertainment, the infamous Astor Place Riots were initially kicked off due to a feud between two Shakespearean actors.")
mall.facts.create(factoid: "The Mall is the only formalistic section of Central Park, which otherwise strived towards a naturalism in its design.")
mall.locimages.create(url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/The_Mall,_Central_Park,_June_2000.JPG/800px-The_Mall,_Central_Park,_June_2000.JPG", alt: "The Mall in early fall.")
mall.locimages.create(url: "http://assets.centralparknyc.org/images/things-to-see-and-do/shakespeare-l.jpg", alt: "Shakespeare's statue in the Literary Walk")

lake = Location.find_by(name: "The Lake (South Shore)")
lake.update(description: "The Southern end of Central Park's Lake hosts some of Central Park's most iconic attractions, including Strawberry Fields and the Bethesda Fountain and Terrace")
lake.landmarks.create(name: "Bethesda Mall and Terrace", description: "Centered around the Angel of the Waters statue, this classic fountain and terrace serves as the location for the ending of John Wick 2", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Angel_of_the_Waters_Fountain_and_Bethesda_Terrace%2C_Central_Park%2C_NYC.jpg/1920px-Angel_of_the_Waters_Fountain_and_Bethesda_Terrace%2C_Central_Park%2C_NYC.jpg")
lake.landmarks.create(name: "Strawberry Fields", description: "A memorial to John Lennon, the entrance to this field at 72nd Street sits right by where the Beatle was murdered outside of his home.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/2960-Central_Park-Strawberry_Fields.JPG/1920px-2960-Central_Park-Strawberry_Fields.JPG")
lake.landmarks.create(name: "Loeb Boathouse", description: "In addition to being a great spot to rent a boat, this boathouse sports a bar for drinking over the pond.", image: "http://onthesetofnewyork.com/locations/whenharrymetsally/Whenharrymetsally109.jpg")
lake.facts.create(factoid: "The Bethesda fountain was a popular gathering place for the Hair generation before becoming a notorious drug spot in the 1970s.")
lake.facts.create(factoid: "The Loeb Boathouse is where Carrie Fisher pulls out her rolodex in When Harry Met Sally to try to find Sally a man.")
lake.create_reference_to_tag_by_name_user_id_and_review("architecture", cheese.id, "That bridge tho.")
lake.create_reference_to_tag_by_name_user_id_and_review("strolling", cheese.id, "This is simply one of my favorite places to walk.")
lake.create_reference_to_tag_by_name_user_id_and_review("kids", cheese.id, "Trying to get my kid into the Beatles by bringing her to the place where John Lennon was shot.")
lake.locimages.create(url: "https://thenypost.files.wordpress.com/2015/08/boathouse-e1524795555719.jpg?quality=90&strip=all&w=618&h=410&crop=1", alt: "The Loeb Boathouse")
lake.locimages.create(url: "https://ephemeralnewyork.files.wordpress.com/2009/05/bethesdafountain.jpg", alt: "Bethesda Fountain")
lake.locimages.create(url: "http://www.centralpark.com/downloads/3396/download/strawberry-fields.jpe?cb=19e288a218f8d4023ee173a221087d2d&w=640", alt: "Strawberry Fields")
lake.locimages.create(url: "https://www.straitstimes.com/sites/default/files/styles/article_pictrure_780x520_/public/articles/2015/10/10/lennon10.jpg?itok=htCiB-Ov&timestamp=1444421248", alt: "Imagine mosaic on Lennon's 75th birthday.")

water = Location.find_by(name: "Conservatory Water")
water.update(description: "Inspired by the design of the Grand Basin model boat pond in Paris’ Luxembourg Gardens, Conservatory Water was created by Frederick Law Olmsted and Calvert Vaux as a place where children and adults alike could experience the pleasure of boating.")
water.landmarks.create(name: "Model Boat Pond", description: "Overlooked by Kerbs Boathouse, visitors can bring or rent a model boat to cruise along a pond featured in many childrens' movies. It's also open for ice skating in the winter.", image: "https://live.staticflickr.com/5296/5542816184_600688df0d_b.jpg")
water.landmarks.create(name: "Alice in Wonderland Sculpture", description: "An 11 foot tall bronze sculpture of Alice and her friends, this sculture is actually approved for climbing by the park.", image: "http://www.centralpark.com/downloads/5135/download/alice.jpe?cb=adffc2e95381fc3159eb65b17097d5f8&w=1800&h=")
water.landmarks.create(name: "Hans Christian Andersen Monument", description: "Central Park's Hans Christian Andersen statue was erected in 1956 to commemorate the author's 150th birthday. The large, bronze statue depicts Andersen seated upon a granite bench, reading from his book The Ugly Duckling. Sculpted by Georg John Lober, this children's statue is meant to be climbed on and is a popular attraction for kids.", image: "http://www.centralpark.com/downloads/1748/download/hans-christian-anderson.jpe?cb=783665e2e86dabe11fdbe675f24e26c4&w=800&h=")
water.facts.create(factoid: "The Model Boat Pond features in the film Stuart Little.")
water.create_reference_to_tag_by_name_user_id_and_review("kids", cheese.id, "My kid yelled 'just like Stuart Little!' while pointing at a rat that crossed us on the way to the Model Boat Pond.")
water.create_reference_to_tag_by_name_user_id_and_review("art", cheese.id, "Got kicked out of the Met for touching sculptures, and then I came here and it was entirely legal. Exciting!")
water.create_reference_to_tag_by_name_user_id_and_review("architecture", cheese.id, "They really don't make buildings the way they used to, do they?")
water.locimages.create(url: "http://www.centralpark.com/downloads/1995/download/conservatory-water.jpe?cb=1c0c259b0b32ab1de90a5a84c9ac0c69&w=1200", alt: "Boat pond with view of skyline")
water.locimages.create(url: "http://assets.centralparknyc.org/images/things-to-see-and-do/kerbs-l.jpg", alt: "Kerbs Boathouse")

turtle = Location.find_by(name: "Turtle Pond")
turtle.update(description: "A quiet area in the park including a castle and an idyllic swamp, this place gets its name for its large turtle population, released into the pond by owners in the 1980s. This area is also home to the Delacorte Theater, New York's home of Shakespeare.")
turtle.landmarks.create(name: "Belvedere Castle", description: "Functioning as a visitor center, Belvedere Castle looks out on the Great Lawn to the North and the Ramble to the South, and is named for its incredible view. It translates to 'Beautiful View' in Italian.", image: "https://bikerentalcentralpark.com/central-park-bike-guide/wp-content/uploads/2017/06/Belvedere-castle-min.jpg")
turtle.landmarks.create(name: "Delacorte Theater", description: "The home of Shakespeare in New York City, this stage is operated by The Public Theater and produces two plays each summer.", image: "https://imgs.6sqft.com/wp-content/uploads/2018/11/01105908/delacorte-theater-flickr.jpg")
turtle.landmarks.create(name: "Swedish Cottage Marionette Theatre", description: "An actual Swedish Cottage built in 1876 as part of Sweden's exhibit for the Centennial Exposition in Philadelphia, this was brought to Central Park where it remains a permanent theater for marionette and puppet performances", image: "https://live.staticflickr.com/94/247028304_58264b15c0_b.jpg")
turtle.landmarks.create(name: "King Jagiello Monument", description: "A monument to the King of Poland and Grand Duke of Lithuania who lived from 1386-1434, the monument celebrates his victory over the Teutonic ORder in 1410 at the Battle of Grunwald, because someone has to.", image: "http://michaelminn.net/newyork/parks/central-park/monuments/king-jagiello/2007-08-28_15-40-51.jpg")
turtle.facts.create(factoid: "The National Weather Service's measurement of the weather in New York is taken from Belvedere castle.")
turtle.create_reference_to_tag_by_name_user_id_and_review("kids", cheese.id, "Where else can you go for a permanent puppet theater in a Swedish cottage? Nowhere. That's why New York's the best friggin city in the world. God bless.")
turtle.create_reference_to_tag_by_name_user_id_and_review("architecture", cheese.id, "This small area has a castle, a theater, and a Swedish Cottage. It's like a zoo for buildings.")
turtle.create_reference_to_tag_by_name_user_id_and_review("wildlife", cheese.id, "Am I turtly enough for the turtle club?")
turtle.locimages.create(url: "http://www.centralpark.com/downloads/2713/download/turtle-pond.jpe?cb=6438982d0020a2297541b1f816d86c27&w=640", alt: "A picture overlooking turtle pond.")
turtle.locimages.create(url: "https://live.staticflickr.com/7367/26752795904_c6d4d178c3_b.jpg", alt: "The pond from Belvedere Castle.")


glawn = Location.find_by(name: "The Great Lawn")
glawn.update(description: "The heart of Central Park, this is home to countless baseball games, playgrounds, an Obelisk, and more.")
glawn.landmarks.create(name: "The Obelisk", description: "Known as \"Cleopatra's Needle\" by New Yorkers, this is the oldest outdoor monument in New York City, the oldest man-made object in Central Park, and dates to around 1450 BCE, when it was erected along with its partner. Both stood in Alexandria since 18 CE, after which one was moved to London while the other was moved to Central Park, after being offered by the Egyptian Khedive to America in exchange for funds to monetize the country.", image: "http://assets.dnainfo.com/generated/photo/2016/04/obelisk-1459878569.jpg/extralarge.jpg")
glawn.landmarks.create(name: "Alexander Hamilton Monument", description: "Donated to Central Park by Alexander Hamilton's son (he had some that didn't die -- they were cut out of the play), this was placed in 1880.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/hamilton-l.jpg")
glawn.landmarks.create(name: "Arthur Ross Pinetum", description: "A four acre landscape that is host to 17 different species of pine trees.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/arthur-ross-pinetum-l.jpg")
glawn.landmarks.create(name: "The Metropolitan Museum of Art", description: "On the East side of Central Park right by the Obelisk is the largest museum in New York and one of the greatest museums in the world.", image: "http://footage.framepool.com/shotimg/qf/705943334-metropolitan-museum-of-art-jacqueline-kennedy-onassis-reservoir-5th-avenue-visions-of-new-york-city.jpg")
glawn.landmarks.create(name: "Summit Rock", description: "West of the Great Lawn lies the highest point of natural elevation in the park. From the West side, you can even see New Jersey, should you want to.", image: "http://www.centralpark.com/downloads/8305/download/summit-rock1.jpg?cb=91f112082dc29141d32bcb6a0438a3fb&w=2048" )
glawn.facts.create(factoid: "The Great Lawn was originally part of New York's reservoir system.")
glawn.create_reference_to_tag_by_name_user_id_and_review("kids", cheese.id, "With more playgrounds than you can shake a stick at and more sticks than you can shake a playground at, your kid will have fun here.")
glawn.create_reference_to_tag_by_name_user_id_and_review("art", cheese.id, "That Obelisk! Wow! And right by the Met.")
glawn.create_reference_to_tag_by_name_user_id_and_review("picnics", cheese.id, "Even on the most crowded day you can always find a spot.")
glawn.locimages.create(url: "http://www.centralpark.com/downloads/5274/download/great-city-great-lawn.jpe?cb=783665e2e86dabe11fdbe675f24e26c4&w=4032", alt: "The lawn with the city in the background.")
glawn.locimages.create(url: "https://d1smv7h0armdzg.cloudfront.net/wp-content/uploads/2014/07/great-lawn-l.jpg", alt: "Crowded day at the Great Lawn as seen overlooking from Turtle Pond.")

reservoir = Location.find_by(name: "The Reservoir")
reservoir.update(description: "Built to hold a billion gallons of water as a temporary water supply while the Croton Water system was shut down for repairs for two weeks, New York now goes through that supply in just four hours. It was decommissioned in 1993, made obsolete by the Third Water Tunnel. It's now a go to spot for joggers.")
reservoir.landmarks.create(name: "South Gatehouse", description: "A small gatehouse overlooking the reservoir.", image: "https://upload.wikimedia.org/wikipedia/commons/e/e2/Central_Park_Reservoir_South_Gatehouse_spring_jeh.jpg")
reservoir.landmarks.create(name: "Gothic Bridge", description: "A gothic style cast iron bridge.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/bridge-28-l.jpg")
reservoir.landmarks.create(name: "Playgrounds", description: "The reservoir is practically flanked by playgrounds, including the Ancient Playground, Safari Playground, and Tarr-Coyne Wild West Playground", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/ancient-playground-l.jpg")
reservoir.landmarks.create(name: "John Purroy Mitchel Memorial", description: "A monument to the youngest ever mayor in New York City who, after a failed re-election bid, enlisted in WWI to serve in the aviation corps, but fell from his plane during a training flight. This is also where the 23rd mile of the marathon is, at the peak of a fairly long incline. If you want to see New Yorkers at their most miserable, this is the place to go.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/john-puroy-mitchell-l.jpg")
reservoir.facts.create(factoid: "The full name of the Reservoir is the Jacqueline Kennedy Onassis reservoir, after Jackie Kennedy Onassis, who used to jog along this path.")
reservoir.create_reference_to_tag_by_name_user_id_and_review("exercise", cheese.id, "When I used to jog, I used to aspire to jog here. Of course, I never made it further than my street.")
reservoir.create_reference_to_tag_by_name_user_id_and_review("kids", cheese.id, "It's tragic that they got rid of the rope swing in the Ancient Playground in the renovation. That used to be the best, most dangerous plaground in the city.")
reservoir.locimages.create(url: "http://assets.centralparknyc.org/images/things-to-see-and-do/reservoir.jpg", alt: "Reservoir with Ghostbusters building in background.")
reservoir.locimages.create(url: "http://footage.framepool.com/shotimg/qf/691818177-jacqueline-kennedy-onassis-reservoir-central-park-manhattan-megacity.jpg", alt: "Reservoir as seen from the sky.")

emeadow = Location.find_by(name: "East Meadow")
emeadow.update(description: "The best spot for picnicking in the park, this sprawling high set of hills gives everyone a place to carve out for themselves.")
emeadow.landmarks.create(name: "Robert Bendheim Playground", description: "A small playground if you're uncomfortable with kids just playing on the rocks.", image: "http://www.centralpark.com/downloads/7734/download/DianaRoss1.jpg?cb=9275f2bc77b6559f12ed438bb40884d7&w=640")
emeadow.facts.create(factoid: "Seriously this is the best place for picnicking in the park.")
emeadow.create_reference_to_tag_by_name_user_id_and_review("picnics", cheese.id, "Grill here on Memorial Day. Everyone does.")
emeadow.locimages.create(url: "https://imgs.6sqft.com/wp-content/uploads/2015/12/20035547/Central-Park-East-Meadow-today-1024x679.jpg", alt: "East Meadow from above")
emeadow.locimages.create(url: "http://michaelminn.net/newyork/parks/central-park/east-meadow/2007-08-28_15-58-37.jpg", alt: "East Meadow with one sunbather.")

nmeadow = Location.find_by(name: "North Meadow")
nmeadow.update(description: "Centered around a series of baseball diamonds, this area also is a great place for a stroll.")
nmeadow.landmarks.create(name: "North Meadow Recreation Center", description: "With a preserved outdoor facade, the interior has basketball and handball courts, as well as a community room for classes, gatherings, and recreational activities. They will loan balls, bats, frisbees, and jump ropes.", image: "http://www.centralpark.com/downloads/8591/download/north-meadow-recreation-center.jpg?cb=3d8658d0ca84f9528be9411c0393c953&w=640")
nmeadow.landmarks.create(name: "North Meadow Butterfly Gardens", description: "These four butterfly gardens are run by volunteers to support butterfly populations.", image: "https://s3.amazonaws.com/assets.centralparknyc.org/images/blog/blooms-2.jpg")
nmeadow.landmarks.create(name: "Springbanks Arch", description: "Connecting the North Meadow to the Loch, this stone span also has a cascade that used to be known as Sabrina's Pool.", image: "http://michaelminn.net/newyork/parks/central-park/bridges/springbanks-arch/2007-08-02_18-51-49.jpg")
nmeadow.facts.create(factoid: "The North Meadow Butterfly Gardens provide habitat for Monarch butterflies migrating through New York City on their way to and from Mexico.")
nmeadow.create_reference_to_tag_by_name_user_id_and_review("exercise", cheese.id, "Handball! Now that's a sport you don't see much of in movies anymore.")
nmeadow.create_reference_to_tag_by_name_user_id_and_review("strolling", cheese.id, "You can see so many butterflies!")
nmeadow.locimages.create(url: "http://www.kermitproject.org/newdeal/centralpark/northmeadow6.jpg", alt: "North Meadow baseball field.")
nmeadow.locimages.create(url: "http://assets.centralparknyc.org/images/things-to-see-and-do/North-Meadow-landscape.jpg", alt: "Natural rock in the back of a North Meadow field, shaded by a tree.")

ghill = Location.find_by(name: "Great Hill")
ghill.update(name: "Great Hill and the Pool", description: "The Northwest corner of the park features a hill perfect for picnics and a segment of wetlands that is beautiful in every season.")
ghill.landmarks.create(name: "Peter J. Sharp Children's Glade", description: "Designed specifically as a glade for children to explore nature and play, the segment features stone and tree trunk seating and fun paths.", image: "http://c3314642.r42.cf0.rackcdn.com/00050798-still1.jpg")
ghill.landmarks.create(name: "Glen Span Arch", description: "Glen Span is one of two rustic arches that form the boundaries of the Ravine, the stream valley of the North Woods. Glen Span arches over the stream, called the Loch, at its south end, with Huddlestone Arch at its north end. Both stone structures are sunken into the Park's landscape.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/glenspan-arch-l.jpg")
ghill.facts.create(factoid: "The pool was originally built by damming a natural stream that was known as Montayne's Rivulet, but now is made of New York City drinking water that comes from a pipe hidden in the rocks on the southern shoreline of the Pool.")
ghill.create_reference_to_tag_by_name_user_id_and_review("strolling", cheese.id, "One of the prettiest areas of the park.")
ghill.create_reference_to_tag_by_name_user_id_and_review("flora", cheese.id, "That weeping willow at the Pool tho")
ghill.create_reference_to_tag_by_name_user_id_and_review("wildlife", cheese.id, "You can see a bunch of different birds, fish, amphibians, anything in the pool!")
ghill.create_reference_to_tag_by_name_user_id_and_review("picnics", cheese.id, "The Great Hill is the spot for picnicking on the West Side.")
ghill.locimages.create(url: "http://assets.centralparknyc.org/images/things-to-see-and-do/great-hill-l.jpg", alt: "Bird's eye view of the pool.")
ghill.locimages.create(url: "http://www.centralpark.com/downloads/4803/download/the-pool.jpe?cb=783665e2e86dabe11fdbe675f24e26c4&w=1200", alt: "The pool, with a weeping willow.")
ghill.locimages.create(url: "http://assets.centralparknyc.org/images/things-to-see-and-do/pool-l.jpg", alt: "rushing water at the pool")

woods = Location.find_by(name: "The North Woods")
woods.update(description: "The closest you can come to a hike in Manhattan and built around the Ravine. While locals will go for a stroll here, it's not unusual to find people in full hiking wear.")
woods.landmarks.create(name: "Loch", description: "This winding, partially natural watercourse runs through the Ravine, and is dammed to create three waterfalls, which are perfect for stumbling upon after a long hike.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/loch-l.jpg")
woods.landmarks.create(name: "Huddlestone Arch", description: "This arch built from huge stones and with a stream running through it is perhaps the only way to separate the North Woods from the Meer.", image: "http://assets.centralparknyc.org/images/things-to-see-and-do/huddlestone-arch-l.jpg")
woods.landmarks.create(name: "Blockhouse No. 1", description: "This small fort in Central Park, overrun with vines, is the second oldest structure in the park after Cleopatra's Needle.", image: "https://upload.wikimedia.org/wikipedia/commons/1/1b/New_York_City_Blockhouse.JPG")
woods.facts.create(factoid: "The City lets fallen trees lie here, preferring to leave this place to plants and wildlife.")
woods.create_reference_to_tag_by_name_user_id_and_review("hiking", cheese.id, "I saw actual hikers here with a fully packed backpack. It's legit.")
woods.create_reference_to_tag_by_name_user_id_and_review("wildlife", cheese.id, "The North Woods: Not just for raccoons baby.")
woods.locimages.create(url: "https://walksofnewyork.com/blog/wp-content/uploads/2014/05/Ravine-600x381.jpg", alt: "One of the Loch's waterfalls.")
woods.locimages.create(url: "https://tclf.org/sites/default/files/thumbnails/image/7678127744_dc00a81dcd_o.jpg", alt: "Huddlestone Arch as seen from the South.")
woods.locimages.create(url: "https://www.twotravelingtexans.com/wp-content/uploads/2016/03/IMG_3039.jpg", alt: "The woods in fall.")
